# Generated by Django 2.1.4 on 2019-02-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zz', models.ImageField(upload_to='')),
            ],
        ),
    ]
