# Generated by Django 2.1.4 on 2019-02-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190228_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml',
            name='zz',
            field=models.ImageField(blank=True, upload_to='ml'),
        ),
    ]
