# Generated by Django 2.1.4 on 2019-02-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190228_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml',
            name='zz',
            field=models.ImageField(height_field='zz_height', max_length='800', upload_to='', width_field='zz_width'),
        ),
    ]
