# Generated by Django 2.1.4 on 2019-02-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190228_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ml',
        ),
    ]
